name: SpringbootPipeline

on:
    push:
        branches: [main,ec2-deploy]

jobs: 
    build:
        runs-on: [ubuntu-latest]
        steps:
            - name: CheckOut Source Code
              uses: actions/checkout@v3

            - name: Java SetUp
              uses: actions/setup-java@v4
              with:
                distribution: 'temurin' # See 'Supported distributions' for available options
                java-version: '17'
            - name: Build the Project
              run: mvn clean install -DskipTests
            
            - name: Login to Docker Hub
              run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

            - name: Build the Docker Image
              run: docker build -t ${{secrets.DOCKER_USERNAME}}/springboot-app .

            - name: publish image to DockerHub
              run: docker push ${{secrets.DOCKER_USERNAME}}/springboot-app:latest

    
    deploy:
        needs: build
        runs-on: [aws-ec2]

        steps:
            - name: Pulll the DOcker Image
              run: docker ${{secrets.DOCKER_USERNAME}}/springboot-app:latest


            - name: Remove the Docker Conatiner if it is already Present
              run: docker rm -f springboot-example-container

            - name: Run the Image as a Conatiner
              run: docker run -d -p 8080:8080 --name springboot-example-container ${{secrets.DOCKER_USERNAME}}/springboot-app:latest

           


